---
- name: Install prerequisites for Node.js
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Download Node.js setup script
  get_url:
    url: https://deb.nodesource.com/setup_18.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755'

- name: Run Node.js setup script
  shell: /tmp/nodesource_setup.sh

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Ensure node and npm installed
  command: node -v
  register: node_version

- name: Show installed Node.js version
  debug:
    var: node_version.stdout
