- name: Install prerequisites for Node.js
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Download Node.js setup script
  get_url:
    url: https://deb.nodesource.com/setup_18.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755'

- name: Run Node.js setup script
  shell: /tmp/nodesource_setup.sh

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Ensure node is installed
  command: node -v
  register: node_version

- name: Show installed Node.js version
  debug:
    var: node_version.stdout

- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone the IOT-Back-End repository
  git:
    repo: https://github.com/Tamratdemse/IOT-Back-End.git
    dest: /opt/IOT-Back-End
    update: yes
