- name: Deploy Node.js on Webserver
  hosts: webservers
  become: yes
  roles:
    - webserver

- name: Deploy MongoDB on DB server
  hosts: dbservers
  become: yes
  roles:
    - dbserver

- name: Deploy Frontend Application
  hosts: frontend # NEW PLAY
  become: yes
  roles:
    - frontend # NEW ROLE